site_name: Exposicion COBIT
dev_addr: 127.0.0.1:8002
# site_url: 
# repo_url: 
# repo_name: <i class="fa fa-git"></i>

theme:
    name: mkdocs
    custom_dir: resources/
extra_css:
    - css/page.css
nav:
    - Problema: todo.md
    - Documentacion:
        - Introduccion: requerimientos/Paola.md
        - Estandares: requerimientos/Mateo.md
        - Caracteristicas: requerimientos/Juan Jose.md
        - Metodologia: requerimientos/Arturo.md
copyright: ©GMDXX
site_author: GMDXX
